[env:esp32dev]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.flash_mode = dio
board_build.partitions = huge_app.csv

lib_deps = 
    t-vk/ESP32 BLE Keyboard @ ^0.3.2
